/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurants;
import java.sql.*;
import javax.swing.*;
import java.awt.Component;
import java.awt.HeadlessException;
import java.awt.TextField;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Rn zid
 */
public class Restaurants extends javax.swing.JFrame {

    /**
     * Creates new form Restaurants
     */
    public Restaurants() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtxtReceipt = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jbilTax2 = new javax.swing.JLabel();
        jChickenBurger = new javax.swing.JLabel();
        jVegBurger = new javax.swing.JLabel();
        jBuffBurger = new javax.swing.JLabel();
        jcheese = new javax.swing.JLabel();
        jFish = new javax.swing.JLabel();
        jtxtCheese = new javax.swing.JTextField();
        jtxtBuff = new javax.swing.JTextField();
        jtxtFish = new javax.swing.JTextField();
        jtxtVeg = new javax.swing.JTextField();
        jtxtChicken = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jbilTax1 = new javax.swing.JLabel();
        JtxtMilkShake = new javax.swing.JTextField();
        jVanila = new javax.swing.JLabel();
        jCVanila = new javax.swing.JLabel();
        jVMilk = new javax.swing.JLabel();
        jMilkShake = new javax.swing.JLabel();
        jCmilk = new javax.swing.JLabel();
        JtxtVanilaMilkShake = new javax.swing.JTextField();
        JtxtClassicVanila = new javax.swing.JTextField();
        JtxtChocolateMilkShake = new javax.swing.JTextField();
        JtxtVanilaCone = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jbilDrinks = new javax.swing.JLabel();
        jTotal = new javax.swing.JLabel();
        jbilMeal = new javax.swing.JLabel();
        jtxtCostOfDrinks = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jtxtCostOfMeal = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jtxtTax = new javax.swing.JTextField();
        jtxtGTotal = new javax.swing.JTextField();
        jbilTax = new javax.swing.JLabel();
        jbilTotal = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jBTotal = new javax.swing.JButton();
        jBReceipt = new javax.swing.JButton();
        jBReset = new javax.swing.JButton();
        jBExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51), 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" Restaurant Billing System");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 8));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rn zid\\Downloads\\download (1).jpg")); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rn zid\\Downloads\\download (1).jpg")); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel2)
            .addComponent(jLabel3)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 1190, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51), 10));

        JtxtReceipt.setBackground(new java.awt.Color(204, 204, 204));
        JtxtReceipt.setColumns(20);
        JtxtReceipt.setRows(5);
        jScrollPane1.setViewportView(JtxtReceipt);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, 390, 550));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51), 10));

        jbilTax2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbilTax2.setText("Meals");

        jChickenBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChickenBurger.setText("Chicken Burger");

        jVegBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jVegBurger.setText("Veg Burger");

        jBuffBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBuffBurger.setText("Buff Burger");

        jcheese.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcheese.setText("Cheese Burger Mix");

        jFish.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jFish.setText("Filet-Fish");

        jtxtCheese.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtCheese.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCheese.setText("0");

        jtxtBuff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtBuff.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBuff.setText("0");

        jtxtFish.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtFish.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtFish.setText("0");
        jtxtFish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFishActionPerformed(evt);
            }
        });

        jtxtVeg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtVeg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtVeg.setText("0");

        jtxtChicken.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChicken.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChicken.setText("0");
        jtxtChicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChickenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jbilTax2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jFish, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcheese, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(jBuffBurger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jVegBurger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jChickenBurger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtCheese, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(jtxtBuff)
                    .addComponent(jtxtVeg, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtChicken)
                    .addComponent(jtxtFish))
                .addGap(33, 33, 33))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jbilTax2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtFish, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFish, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jChickenBurger)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jVegBurger)
                                    .addComponent(jtxtVeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBuffBurger)
                                    .addComponent(jtxtBuff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jcheese))
                            .addComponent(jtxtCheese, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jtxtChicken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 400, 320));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51), 10));

        jbilTax1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbilTax1.setText("Drinks");

        JtxtMilkShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JtxtMilkShake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JtxtMilkShake.setText("0");

        jVanila.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jVanila.setText("Vanila cone");

        jCVanila.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCVanila.setText("Classic Vanila");

        jVMilk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jVMilk.setText("Vanila Milk Shake");

        jMilkShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMilkShake.setText("Milk Shake");

        jCmilk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCmilk.setText("Chocolate Milk Shake");

        JtxtVanilaMilkShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JtxtVanilaMilkShake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JtxtVanilaMilkShake.setText("0");

        JtxtClassicVanila.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JtxtClassicVanila.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JtxtClassicVanila.setText("0");

        JtxtChocolateMilkShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JtxtChocolateMilkShake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JtxtChocolateMilkShake.setText("0");

        JtxtVanilaCone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JtxtVanilaCone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JtxtVanilaCone.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbilTax1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jCmilk))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jMilkShake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jVanila, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCVanila, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jVMilk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(JtxtClassicVanila, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(JtxtVanilaCone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addComponent(JtxtMilkShake, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(JtxtChocolateMilkShake))
                    .addComponent(JtxtVanilaMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jbilTax1)
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jMilkShake)
                    .addComponent(JtxtMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JtxtVanilaCone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jVanila))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jCVanila)
                        .addGap(23, 23, 23)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jVMilk)
                            .addComponent(JtxtVanilaMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(JtxtClassicVanila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JtxtChocolateMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCmilk))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 380, 320));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51), 10));

        jbilDrinks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbilDrinks.setText("Cost Of Drinks");

        jTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTotal.setText(" Total");

        jbilMeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbilMeal.setText("Cost Of Meal");

        jtxtCostOfDrinks.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtCostOfDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCostOfDrinksActionPerformed(evt);
            }
        });

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });

        jtxtCostOfMeal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtCostOfMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCostOfMealActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbilDrinks, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jbilMeal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(jtxtCostOfDrinks, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtCostOfMeal, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(34, 34, 34))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbilMeal)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jtxtCostOfMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jtxtCostOfDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jbilDrinks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTotal)))
                .addGap(31, 31, 31))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 400, 130));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51), 10));

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTaxActionPerformed(evt);
            }
        });

        jtxtGTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jbilTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbilTax.setText("Tax");

        jbilTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbilTotal.setText("Grand Total");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbilTax, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbilTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(jtxtGTotal))
                .addGap(61, 61, 61))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbilTax)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbilTotal)
                    .addComponent(jtxtGTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 380, 130));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51), 10));

        jBTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBTotal.setText("Total");
        jBTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTotalActionPerformed(evt);
            }
        });

        jBReceipt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBReceipt.setText("Receipt");
        jBReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReceiptActionPerformed(evt);
            }
        });

        jBReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBReset.setText("Reset");
        jBReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBResetActionPerformed(evt);
            }
        });

        jBExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBExit.setText("Exit");
        jBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jBTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jBReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jBReset, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jBExit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBTotal)
                        .addComponent(jBReceipt)
                        .addComponent(jBReset))
                    .addComponent(jBExit))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 790, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReceiptActionPerformed
        
        //==============================================================
        
        int refs= 12345+ (int) (Math.random()*4328);
        
        //==============================================================
        
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-mm-yyyy");
        Tdate.format(timer.getTime());
        
        
        JtxtReceipt.append(" \n\t WELCOME TO LUMANTI \n\n"
        +"\n Reference: "+ refs +
                 "\n================================================\n" + 
                "   Meals:\t\t" + jtxtCostOfMeal.getText()+"\n\n"+
                "   Drinks:\t\t" + jtxtCostOfDrinks.getText()+"\n\n"+
                 "   TotalCost:\t\t" + jtxtTotal.getText()+"\n\n" +
                "================================================"+"\n\n"+
                  "   Tax:\t\t" + jtxtTax.getText()+"\n\n" +
                "   Grand Total:\t\t" + jtxtGTotal.getText()+"\n\n"+
                "================================================"+
                "\n   Date:"+ Tdate.format(timer.getTime())+
                 "\n   Time:" + tTime.format(timer.getTime())+
                "\n\n===================THANK YOU===================="+
                "\n=================PLEASE VISIT AGAIN==============="
                  );
               
    }//GEN-LAST:event_jBReceiptActionPerformed

    private void jtxtTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTaxActionPerformed

    private void jtxtCostOfDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCostOfDrinksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCostOfDrinksActionPerformed

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalActionPerformed

    private void jtxtCostOfMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCostOfMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCostOfMealActionPerformed

    private void jtxtFishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFishActionPerformed

    private void jtxtChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChickenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChickenActionPerformed

    private void jBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitActionPerformed
        // TODO add your handling code here:
        SubClass_Child iExit =new SubClass_Child();
        iExit.iExitSystem();
    }//GEN-LAST:event_jBExitActionPerformed

    private void jBResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBResetActionPerformed
        JTextField cleartext = null;
        //=================================================
        for (Component c:jPanel4.getComponents())
        {
            if(c.getClass().toString().contains("javax.swing.JTextField"))
            {
                cleartext =(JTextField)c;
                cleartext.setText("0");
            }
        }
        //=================================================
        for (Component c:jPanel5.getComponents())
        {
            if(c.getClass().toString().contains("javax.swing.JTextField"))
            {
                cleartext =(JTextField)c;
                cleartext.setText("0");
            }
        }
        //=================================================
        for (Component c:jPanel6.getComponents())
        {
            if(c.getClass().toString().contains("javax.swing.JTextField"))
            {
                cleartext =(JTextField)c;
                cleartext.setText("");
            }
        }
        //=================================================
        for (Component c:jPanel7.getComponents())
        {
            if(c.getClass().toString().contains("javax.swing.JTextField"))
            {
                cleartext =(JTextField)c;
                cleartext.setText("");
            }
        }
       JtxtReceipt.setText(null); 
    }//GEN-LAST:event_jBResetActionPerformed

    private void jBTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTotalActionPerformed
    SubClass_Child ItemCost = new SubClass_Child();
    double iTax, iTotal, iGTotal, iCostOfMeal, iCostOfDrinks;
    ItemCost.FiletFish = ItemCost.pFiletFish * Double.parseDouble(jtxtFish.getText());
    ItemCost.ChickenBurger = ItemCost.pChickenBurger * Double.parseDouble(jtxtChicken.getText());
    ItemCost.VegBurger = ItemCost.pVegBurger * Double.parseDouble(jtxtVeg.getText());
    ItemCost.BuffBurger = ItemCost.pBuffBurger * Double.parseDouble(jtxtBuff.getText());
    ItemCost.CheeseBurgerMix = ItemCost.pCheeseBurgerMix * Double.parseDouble(jtxtCheese.getText());
    
    ItemCost.MilkShake = ItemCost.pMilkShake * Double.parseDouble(JtxtMilkShake.getText());
    ItemCost.VanillaCone = ItemCost.pVanillaCone * Double.parseDouble(JtxtVanilaCone.getText());
    ItemCost.ClassicVanila = ItemCost.pClassicVanila * Double.parseDouble(JtxtClassicVanila.getText());
    ItemCost.VanillaMilkShake = ItemCost.pVanillaMilkShake * Double.parseDouble(JtxtVanilaMilkShake.getText());
    ItemCost.ChocolateMilkShake= ItemCost.pChocolateMilkShake * Double.parseDouble(JtxtChocolateMilkShake.getText());
    
    
    iTotal= ItemCost.GetAmount();
    iTax= ItemCost.cFindTax(iTotal);
    iGTotal = iTotal + iTax;
    
    iCostOfMeal=ItemCost.FiletFish + ItemCost.ChickenBurger + ItemCost.BuffBurger + ItemCost.VegBurger + ItemCost.CheeseBurgerMix;
    
    String CostOfMeal = String.format("RS %.2f", iCostOfMeal);
    jtxtCostOfMeal.setText(CostOfMeal);

    iCostOfDrinks=ItemCost.MilkShake + ItemCost.ChocolateMilkShake + ItemCost.ClassicVanila + ItemCost.VanillaCone + ItemCost.VanillaMilkShake;
    
    String CostOfDrinks = String.format("RS %.2f", iCostOfDrinks);
    jtxtCostOfDrinks.setText(CostOfDrinks);
    
    
    String Total = String.format("RS %.2f", iTotal);
    jtxtTotal.setText(Total);
    
    String Tax = String.format("RS %.2f", iTax);
    jtxtTax.setText(Tax);
    
    String GTotal = String.format("RS %.2f", iGTotal);
    jtxtGTotal.setText(GTotal);

    
     String username="root";
    String password ="";
     try{ 
         Class.forName("com.mysql.jdbc.Driver");
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/billrecord",username,password)) {
            String Query ="INSERT INTO billrecord(COMeal, CODrinks,Total,Tax,GTotal) VALUES('"+jtxtCostOfMeal.getText()+"','"+jtxtCostOfDrinks.getText()+"','"+jtxtTotal.getText()+"','"+jtxtTax.getText()+"','"+jtxtGTotal.getText()+"')";
            Statement st= con.createStatement();
            st.executeUpdate(Query);
            
            
            JOptionPane.showMessageDialog(null,"Record Added");
            
//            jtxtCostOfMeal.setText(null);
//            jtxtCostOfDrinks.setText(null);
//            jtxtTotal.setText(null);
//            jtxtTax.setText(null);
//            jtxtGTotal.setText(null);
        }
    }
    catch(HeadlessException | ClassNotFoundException | SQLException e){
        JOptionPane.showMessageDialog(null, e.toString());
    }
// TODO add your handling code here:
    }//GEN-LAST:event_jBTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JtxtChocolateMilkShake;
    private javax.swing.JTextField JtxtClassicVanila;
    private javax.swing.JTextField JtxtMilkShake;
    private javax.swing.JTextArea JtxtReceipt;
    private javax.swing.JTextField JtxtVanilaCone;
    private javax.swing.JTextField JtxtVanilaMilkShake;
    private javax.swing.JButton jBExit;
    private javax.swing.JButton jBReceipt;
    private javax.swing.JButton jBReset;
    private javax.swing.JButton jBTotal;
    private javax.swing.JLabel jBuffBurger;
    private javax.swing.JLabel jCVanila;
    private javax.swing.JLabel jChickenBurger;
    private javax.swing.JLabel jCmilk;
    private javax.swing.JLabel jFish;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jMilkShake;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jTotal;
    private javax.swing.JLabel jVMilk;
    private javax.swing.JLabel jVanila;
    private javax.swing.JLabel jVegBurger;
    private javax.swing.JLabel jbilDrinks;
    private javax.swing.JLabel jbilMeal;
    private javax.swing.JLabel jbilTax;
    private javax.swing.JLabel jbilTax1;
    private javax.swing.JLabel jbilTax2;
    private javax.swing.JLabel jbilTotal;
    private javax.swing.JLabel jcheese;
    private javax.swing.JTextField jtxtBuff;
    private javax.swing.JTextField jtxtCheese;
    private javax.swing.JTextField jtxtChicken;
    private javax.swing.JTextField jtxtCostOfDrinks;
    private javax.swing.JTextField jtxtCostOfMeal;
    private javax.swing.JTextField jtxtFish;
    private javax.swing.JTextField jtxtGTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JTextField jtxtVeg;
    // End of variables declaration//GEN-END:variables
}
